// Code generated by jtd-codegen for TypeScript v0.2.1

export interface Announcement {
  /**
   * The content of the announcement
   */
  content: string;

  /**
   * The date the announcement is made
   */
  date: string;

  /**
   * The title of the announcement
   */
  title: string;
}
