// Code generated by jtd-codegen for TypeScript v0.2.1

export interface ClubEvent {
  /**
   * A short description of the event
   */
  description: string;

  /**
   * The end date and time of the event
   */
  end: string;

  /**
   * More information about the event (e.g. location, requirements, etc.)
   */
  information: string;

  /**
   * Whether the event is schoolwide (i.e. not associated with a particular set
   * of clubs)
   */
  isSchoolWideEvent: boolean;

  /**
   * The name of the club
   */
  name: string;

  /**
   * The start date and time of the event
   */
  start: string;
}
