// Code generated by jtd-codegen for TypeScript v0.2.1

export interface Club {
  /**
   * The leaders of the club
   */
  clubLeaders: string;

  /**
   * The club's equity statement
   */
  equityStatement: string;

  /**
   * Instructions about how to join the club
   */
  joinInstructions: string;

  /**
   * The meeting times of the club
   */
  meetingTimes: string;

  /**
   * The name of the club
   */
  name: string;

  /**
   * A short description of the club
   */
  shortDescription: string;

  /**
   * A unique identifier for the club
   */
  slug: string;

  /**
   * The supervisors of the club
   */
  staffSupervisor: string;

  /**
   * A comma separated list of categories the club belongs to
   */
  categories?: string;

  /**
   * Extra information about the club
   */
  extraInformation?: string;

  /**
   * Online platforms to find more information about the club (e.g. Instagram,
   * Discord, etc.)
   */
  onlinePlatforms?: string;

  /**
   * The time commitment members need to participate in the club
   */
  timeCommitment?: string;
}
