name: GitHub Pages Deploy Workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install

      - name: Build and Deploy to GitHub Pages
        run: sh scripts/deploy-frontend.sh
