name: GitHub Pages Deploy Workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Use pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2

      - name: Install dependencies and build frontend
        run: pnpm prune:frontend && pnpm install && pnpm build:frontend
        env:
          VITE_AUTO_UPDATE_SERVER_URL: https://vpci-clubs-auto-update.herokuapp.com
          VITE_SPREADSHEET_ID: 1vHB0J6uAdi4tT37KfhACxfpqyCmsN_Y8HD9cJ8T1FFI
          VITE_SPREADSHEET_CLUBS_SHEET_ID: '1221049338'

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: frontend/dist
